### PR TITLE
Update to vapor3

### PR DESCRIPTION
**Pull request by heidipuk**
The package have been upgraded to Swift 4.2 and Vapor 3.

### CODE REVIEW

**Comment by steffendsommer** [comment]
@BrettRToomey are you up for reviewing this PR?

**Comment by BrettRToomey** [comment]
Everything looks great so far! @heidipuk It would be nice if we could remove Vapor as a dependency as it's not really being used. Do you know if that's possible? I can try and help with this. Thanks

**Comment by heidipuk** [comment]
@BrettRToomey , I have removed Vapor as a dependency and added the SwiftNio Core package in stead, as we use quite a lot of their functionality in the Parser.

**Comment by BrettRToomey** [comment]
@heidipuk I appreciate that a lot! Do you know exactly what we used? It would be nice to know so that I can go in and remove them in the future. This is a small package and it'd be nice to have no dependencies.

Thanks again for the PR!

**Review by BrettRToomey — APPROVED** [review]

**Comment by heidipuk** [comment]
@BrettRToomey , It is two parts from Core that we use: An extension to Byte, which is found in "Core3.4.4/Bits/Byte-Control". We actually only use three cases, `.comma`, `.percent` and `.semicolon`. (We do however use a few more cases in the test)
The second is a function called `convertFromData() -> Data`, which can be found in "Core3.4.4/Core/LosslessDataConvertible". We use the version that extends the array.

**Comment by BrettRToomey** [comment]
@heidipuk Thanks a lot! I will look into it!

**Comment by heidipuk** [comment]
Cool, I can also do it if you want :)

**Comment by BrettRToomey** [comment]
@heidipuk If you're up for the task, you're more than welcome to look at it. Feel free to DM me on Slack if you have any questions.

**Pull request merged**
